#!/bin/bash

loads=($(mpstat -P ALL 1 1 | awk '/Average:/ && $2 ~ /[0-9]/ {print $3}' | tr ',' '.'))
average=$( python -c "print(int(float('${loads[0]}') + float('${loads[1]}') + float('${loads[2]}') + float('${loads[3]}')))")
average2="$average %"
if [[ $average -gt 60 ]]; then
    echo -e "%{F-$c22330}$average2%{F-} | "
else
    echo -e "$average2 | "
fi
